require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ComponentesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Componente. As you add validations to Componente, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ComponentesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all componentes as @componentes" do
      componente = Componente.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:componentes)).to eq([componente])
    end
  end

  describe "GET #show" do
    it "assigns the requested componente as @componente" do
      componente = Componente.create! valid_attributes
      get :show, {:id => componente.to_param}, valid_session
      expect(assigns(:componente)).to eq(componente)
    end
  end

  describe "GET #new" do
    it "assigns a new componente as @componente" do
      get :new, {}, valid_session
      expect(assigns(:componente)).to be_a_new(Componente)
    end
  end

  describe "GET #edit" do
    it "assigns the requested componente as @componente" do
      componente = Componente.create! valid_attributes
      get :edit, {:id => componente.to_param}, valid_session
      expect(assigns(:componente)).to eq(componente)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Componente" do
        expect {
          post :create, {:componente => valid_attributes}, valid_session
        }.to change(Componente, :count).by(1)
      end

      it "assigns a newly created componente as @componente" do
        post :create, {:componente => valid_attributes}, valid_session
        expect(assigns(:componente)).to be_a(Componente)
        expect(assigns(:componente)).to be_persisted
      end

      it "redirects to the created componente" do
        post :create, {:componente => valid_attributes}, valid_session
        expect(response).to redirect_to(Componente.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved componente as @componente" do
        post :create, {:componente => invalid_attributes}, valid_session
        expect(assigns(:componente)).to be_a_new(Componente)
      end

      it "re-renders the 'new' template" do
        post :create, {:componente => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested componente" do
        componente = Componente.create! valid_attributes
        put :update, {:id => componente.to_param, :componente => new_attributes}, valid_session
        componente.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested componente as @componente" do
        componente = Componente.create! valid_attributes
        put :update, {:id => componente.to_param, :componente => valid_attributes}, valid_session
        expect(assigns(:componente)).to eq(componente)
      end

      it "redirects to the componente" do
        componente = Componente.create! valid_attributes
        put :update, {:id => componente.to_param, :componente => valid_attributes}, valid_session
        expect(response).to redirect_to(componente)
      end
    end

    context "with invalid params" do
      it "assigns the componente as @componente" do
        componente = Componente.create! valid_attributes
        put :update, {:id => componente.to_param, :componente => invalid_attributes}, valid_session
        expect(assigns(:componente)).to eq(componente)
      end

      it "re-renders the 'edit' template" do
        componente = Componente.create! valid_attributes
        put :update, {:id => componente.to_param, :componente => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested componente" do
      componente = Componente.create! valid_attributes
      expect {
        delete :destroy, {:id => componente.to_param}, valid_session
      }.to change(Componente, :count).by(-1)
    end

    it "redirects to the componentes list" do
      componente = Componente.create! valid_attributes
      delete :destroy, {:id => componente.to_param}, valid_session
      expect(response).to redirect_to(componentes_url)
    end
  end

end
