require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ContratoProdutosController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # ContratoProduto. As you add validations to ContratoProduto, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ContratoProdutosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all contrato_produtos as @contrato_produtos" do
      contrato_produto = ContratoProduto.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:contrato_produtos)).to eq([contrato_produto])
    end
  end

  describe "GET #show" do
    it "assigns the requested contrato_produto as @contrato_produto" do
      contrato_produto = ContratoProduto.create! valid_attributes
      get :show, {:id => contrato_produto.to_param}, valid_session
      expect(assigns(:contrato_produto)).to eq(contrato_produto)
    end
  end

  describe "GET #new" do
    it "assigns a new contrato_produto as @contrato_produto" do
      get :new, {}, valid_session
      expect(assigns(:contrato_produto)).to be_a_new(ContratoProduto)
    end
  end

  describe "GET #edit" do
    it "assigns the requested contrato_produto as @contrato_produto" do
      contrato_produto = ContratoProduto.create! valid_attributes
      get :edit, {:id => contrato_produto.to_param}, valid_session
      expect(assigns(:contrato_produto)).to eq(contrato_produto)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new ContratoProduto" do
        expect {
          post :create, {:contrato_produto => valid_attributes}, valid_session
        }.to change(ContratoProduto, :count).by(1)
      end

      it "assigns a newly created contrato_produto as @contrato_produto" do
        post :create, {:contrato_produto => valid_attributes}, valid_session
        expect(assigns(:contrato_produto)).to be_a(ContratoProduto)
        expect(assigns(:contrato_produto)).to be_persisted
      end

      it "redirects to the created contrato_produto" do
        post :create, {:contrato_produto => valid_attributes}, valid_session
        expect(response).to redirect_to(ContratoProduto.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved contrato_produto as @contrato_produto" do
        post :create, {:contrato_produto => invalid_attributes}, valid_session
        expect(assigns(:contrato_produto)).to be_a_new(ContratoProduto)
      end

      it "re-renders the 'new' template" do
        post :create, {:contrato_produto => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested contrato_produto" do
        contrato_produto = ContratoProduto.create! valid_attributes
        put :update, {:id => contrato_produto.to_param, :contrato_produto => new_attributes}, valid_session
        contrato_produto.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested contrato_produto as @contrato_produto" do
        contrato_produto = ContratoProduto.create! valid_attributes
        put :update, {:id => contrato_produto.to_param, :contrato_produto => valid_attributes}, valid_session
        expect(assigns(:contrato_produto)).to eq(contrato_produto)
      end

      it "redirects to the contrato_produto" do
        contrato_produto = ContratoProduto.create! valid_attributes
        put :update, {:id => contrato_produto.to_param, :contrato_produto => valid_attributes}, valid_session
        expect(response).to redirect_to(contrato_produto)
      end
    end

    context "with invalid params" do
      it "assigns the contrato_produto as @contrato_produto" do
        contrato_produto = ContratoProduto.create! valid_attributes
        put :update, {:id => contrato_produto.to_param, :contrato_produto => invalid_attributes}, valid_session
        expect(assigns(:contrato_produto)).to eq(contrato_produto)
      end

      it "re-renders the 'edit' template" do
        contrato_produto = ContratoProduto.create! valid_attributes
        put :update, {:id => contrato_produto.to_param, :contrato_produto => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested contrato_produto" do
      contrato_produto = ContratoProduto.create! valid_attributes
      expect {
        delete :destroy, {:id => contrato_produto.to_param}, valid_session
      }.to change(ContratoProduto, :count).by(-1)
    end

    it "redirects to the contrato_produtos list" do
      contrato_produto = ContratoProduto.create! valid_attributes
      delete :destroy, {:id => contrato_produto.to_param}, valid_session
      expect(response).to redirect_to(contrato_produtos_url)
    end
  end

end
