require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe EquipamentoComponentesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # EquipamentoComponente. As you add validations to EquipamentoComponente, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EquipamentoComponentesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all equipamento_componentes as @equipamento_componentes" do
      equipamento_componente = EquipamentoComponente.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:equipamento_componentes)).to eq([equipamento_componente])
    end
  end

  describe "GET #show" do
    it "assigns the requested equipamento_componente as @equipamento_componente" do
      equipamento_componente = EquipamentoComponente.create! valid_attributes
      get :show, {:id => equipamento_componente.to_param}, valid_session
      expect(assigns(:equipamento_componente)).to eq(equipamento_componente)
    end
  end

  describe "GET #new" do
    it "assigns a new equipamento_componente as @equipamento_componente" do
      get :new, {}, valid_session
      expect(assigns(:equipamento_componente)).to be_a_new(EquipamentoComponente)
    end
  end

  describe "GET #edit" do
    it "assigns the requested equipamento_componente as @equipamento_componente" do
      equipamento_componente = EquipamentoComponente.create! valid_attributes
      get :edit, {:id => equipamento_componente.to_param}, valid_session
      expect(assigns(:equipamento_componente)).to eq(equipamento_componente)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new EquipamentoComponente" do
        expect {
          post :create, {:equipamento_componente => valid_attributes}, valid_session
        }.to change(EquipamentoComponente, :count).by(1)
      end

      it "assigns a newly created equipamento_componente as @equipamento_componente" do
        post :create, {:equipamento_componente => valid_attributes}, valid_session
        expect(assigns(:equipamento_componente)).to be_a(EquipamentoComponente)
        expect(assigns(:equipamento_componente)).to be_persisted
      end

      it "redirects to the created equipamento_componente" do
        post :create, {:equipamento_componente => valid_attributes}, valid_session
        expect(response).to redirect_to(EquipamentoComponente.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved equipamento_componente as @equipamento_componente" do
        post :create, {:equipamento_componente => invalid_attributes}, valid_session
        expect(assigns(:equipamento_componente)).to be_a_new(EquipamentoComponente)
      end

      it "re-renders the 'new' template" do
        post :create, {:equipamento_componente => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested equipamento_componente" do
        equipamento_componente = EquipamentoComponente.create! valid_attributes
        put :update, {:id => equipamento_componente.to_param, :equipamento_componente => new_attributes}, valid_session
        equipamento_componente.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested equipamento_componente as @equipamento_componente" do
        equipamento_componente = EquipamentoComponente.create! valid_attributes
        put :update, {:id => equipamento_componente.to_param, :equipamento_componente => valid_attributes}, valid_session
        expect(assigns(:equipamento_componente)).to eq(equipamento_componente)
      end

      it "redirects to the equipamento_componente" do
        equipamento_componente = EquipamentoComponente.create! valid_attributes
        put :update, {:id => equipamento_componente.to_param, :equipamento_componente => valid_attributes}, valid_session
        expect(response).to redirect_to(equipamento_componente)
      end
    end

    context "with invalid params" do
      it "assigns the equipamento_componente as @equipamento_componente" do
        equipamento_componente = EquipamentoComponente.create! valid_attributes
        put :update, {:id => equipamento_componente.to_param, :equipamento_componente => invalid_attributes}, valid_session
        expect(assigns(:equipamento_componente)).to eq(equipamento_componente)
      end

      it "re-renders the 'edit' template" do
        equipamento_componente = EquipamentoComponente.create! valid_attributes
        put :update, {:id => equipamento_componente.to_param, :equipamento_componente => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested equipamento_componente" do
      equipamento_componente = EquipamentoComponente.create! valid_attributes
      expect {
        delete :destroy, {:id => equipamento_componente.to_param}, valid_session
      }.to change(EquipamentoComponente, :count).by(-1)
    end

    it "redirects to the equipamento_componentes list" do
      equipamento_componente = EquipamentoComponente.create! valid_attributes
      delete :destroy, {:id => equipamento_componente.to_param}, valid_session
      expect(response).to redirect_to(equipamento_componentes_url)
    end
  end

end
